export default {
    login: {
        userName: 'Username',
        password: 'Password',
        login: 'Login',
        loginError: 'Login failed',
        loginSuccess: 'Login success',
        loginErrorTip: 'Username or password error',
        loginSuccessTip: 'Login success',
        loginBtn: 'Login',
        back: 'Welcome back',
        details: 'Welcome back! Please enter your details',
        forget: 'Forget password',
        remember: 'Remember me',
        account: 'Dont have account',
        register: 'Sign up',
        modifyPassword: 'Modify password',
        personInfo: 'Personal information',
        logout: 'Logout',
    },
    menu: {
        serviceManager: 'Service Manager',
        fileManager: 'File Manager',
        fileAll: 'All Files',
        recyle: 'Recycle Bin',
        myShare: 'My Share',
        myCollection: 'My Collection',
        receiveShare: 'Receive Share',
    },
    file: {
        async: 'Async file',
        name: 'Name',
        size: 'Size',
        updateTime: 'Update time',
        increase: 'Increase',
        delete: 'Delete',
        upload: 'Upload',
        more: 'More',
        share: 'Share',
        download: 'Download',
        move: 'Move',
        rename: 'Rename',
        copy: 'Copy',
        edit: 'Edit',
    }
}