export default {
    login: {
        userName: '用户名',
        password: '密码',
        login: '登录',
        loginError: '登录失败',
        loginSuccess: '登录成功',
        loginErrorTip: '用户名或密码错误',
        loginSuccessTip: '登录成功',
        loginBtn: '登录',
        back: '欢迎回来',
        details: '欢迎回来！请填写您的详细信息',
        forget: '忘记密码',
        remember: '记住我',
        account: '还没有账号?',
        register: '注册',
        modifyPassword: '修改密码',
        personInfo: '个人信息',
        logout: '退出登录',
    },
    menu: {
        serviceManager: '个人网盘',
        fileManager: '文件管理',
        fileAll: '全部文件',
        recyle: '回收站',
        myShare: '我的分享',
        myCollection: '我的收藏',
        receiveShare: '收到的分享',
    },
    file: {
        async: '文件同步',
        name: '文件名',
        size: '大小',
        updateTime: '修改时间',
        increase: '新增文件夹',
        delete: '删除',
        upload: '上传',
        more: '更多操作',
        share: '分享',
        download: '下载',
        move: '移动',
        rename: '重命名',
        copy: '复制',
        edit: '编辑',
    }
}